### ISSUE TITLE
Can't find 'stripped' directory in target build

### ISSUE THREAD

**Issue by samgos** [raboof/sbt-reproducible-builds#113]
Hello, attempting to use this library and even tried a build with your test samples but I cannot find any remainder of this output directory, any chance you could help clarify where it is or suggest an approach to build with it?

Tried builds via sbt on the command line and in IDEA.

Much appreciated.

**Comment by raboof** [comment]
For example for the `sbt-reproducible-builds` project, `sbt package` will produce
`target/scala-2.12/sbt-1.0/stripped/sbt-reproducible-builds-0.21+11-77ee54d6.jar`.

I'll add the `sbt package` step to the README. Does that work for you or are you still missing the result?

**Comment by raboof** [comment]
(feel free to reopen when the issue persists)
