### ISSUE TITLE
Also make assemblies reproducible

### ISSUE THREAD

**Issue by raboof** [raboof/sbt-reproducible-builds#127]

**Comment by somdoron** [comment]
By assemblies you mean sbt-assembly plugin? 
https://github.com/sbt/sbt-assembly

**Comment by raboof** [comment]
Indeed!

**Comment by somdoron** [comment]
Nice, I would to try to contribute this, if you pointers that would be great.

**Comment by raboof** [comment]
> Nice, I would to try to contribute this

That would be awesome!

> if you pointers that would be great.

Sure: a tricky part is that we want to 'hook into' the assembly tasks when the build by the user uses sbt-assembly, but we don't want to introduce sbt-assembly to the users' build.

Luckily we already have an example of this: sbt-native-packager and sbt-gpg are the same in this sense. They are included as 'Provided' dependencies in `build.sbt`. To avoid problems for users that don't have these plugins, we only refer to classes from these jars in `Helpers` classes (`src/main/scala/GpgHelpers.scala`, `src/main/scala/SbtNativePackagerHelpers.scala`.

Then in `ReproducibleBuildsPlugin` we check if those plugins are present by looking at the classpath (`universalPluginOnClasspath`, `gpgPluginOnClasspath`) and only load the helpers when appropriate.

Does that help?

**Comment by somdoron** [comment]
Yes. I will take a look at how the SbtNativePackager works.
My guess is that I have to strip the jar from any timestamps and make sure the order is deterministic?

**Comment by somdoron** [comment]
It might be simpler, only calling `ReproducibleBuildsPlugin.postProcessZip` on the Jar?

**Comment by raboof** [comment]
> It might be simpler, only calling `ReproducibleBuildsPlugin.postProcessZip` on the Jar?

That sounds like a great first step, though perhaps we want to do more later. Try it and see ;).

**Comment by somdoron** [comment]
great, will try at the weekend

**Comment by raboof** [comment]
Thanks for the contribution in #152! Let's close this issue. If there's any further things we can do to improve reproducibility of assemblies we can file those as separate tickets.

**Comment by somdoron** [comment]
Thanks for helping! 

Any release soon? Or a snapshot version?

**Comment by raboof** [comment]
> Or a snapshot version?

I think we should set up snapshot publishing, yes :)

> Any release soon?

Have you had an opportunity to test the assembly post-processing on a real-world project yet? Was it successful? If so I'm happy to release a new version.

**Comment by somdoron** [comment]
I will do it over the weekend and let you know. Now that I have this
https://github.com/aevea/action-kaniko/issues/5 as well, I'm ready to do an
end to end test.

**Comment by somdoron** [comment]
I can confirm that the plugin works. Files are identical.
