### ISSUE TITLE
Make stripped 'assembly' executable

### ISSUE THREAD

**Issue by raboof** [raboof/sbt-reproducible-builds#155]
It looks like the 'assembly' task makes its output jar executable, but our 'stripped' version is not.

This causes problems like in https://github.com/akka/akka-grpc/pull/1027

Could you have a look @somdoron?

**Comment by somdoron** [comment]
executable like `chmod +x`?

**Comment by raboof** [comment]
Yes (but platform-agnostic I suppose ;) )

**Comment by somdoron** [comment]
not so sure...
https://github.com/sbt/sbt-assembly/blob/edd35cfbaf05c3465371b63d38fda8ac579d766c/src/main/scala/sbtassembly/Assembly.scala#L67

**Comment by raboof** [comment]
Interesting! That snippet seems only relevant when `prependShellScript` is set though, I'm not sure that's the case for the akka-grpc example. But might be worth looking into.

**Comment by somdoron** [comment]
what about this:

```
assembly := {
        val jar = assembly.value
        val stripped = ReproducibleBuildsPlugin.postProcessJar(jar)

        try {
          sys.process.Process("chmod", Seq(s"--reference=${jar.toString}", stripped.toString)).!
        }
        catch {
          case e: IOException => log.warn("Could not run 'chmod' on jarfile. Perhaps chmod command is not available?")
        }

        stripped
      }
```

**Comment by somdoron** [comment]
By the way, scala-grpc is using the prependShellScript option.

https://github.com/akka/akka-grpc/blob/master/build.sbt#L37

**Comment by raboof** [comment]
Aaah missed that, good one.

**Comment by somdoron** [comment]
@raboof I'm afraid it won't be easy to support prependShellScript, as the assembly file ends up not being a valid zip file. I suggest that if the prependShellScript is set we will print a warning and not try to strip the file.

**Comment by raboof** [comment]
Aah, OK, sounds good to me!
