### ISSUE TITLE
packageBin not affected

### ISSUE THREAD

**Issue by jtjeferreira** [raboof/sbt-reproducible-builds#9]
I was trying the plugin but it was not producing any effect, so I copied the plugin content to my build configuration. Only after I changed 
```
packageBin in (Compile, packageBin) ~= { bin =>
```
to 
```
packageBin in Compile ~= { bin =>
```

it started working...

It seems that 76d0b2bd2c58bf81af8309ba6b5e5cf51928b5c1 changed things...

**Comment by raboof** [comment]
Interesting (and surprising)! We should definitely start adding 'scripted' tests...

**Comment by raboof** [comment]
Rolled back that commit and added a simple scripted test to check it. Let me know if it now works for you!

**Comment by jtjeferreira** [comment]
Thanks for the fix. It is working now. However would be extra cool that the final jar would be called `simple_2.12-0.1.0-SNAPSHOT.jar` instead `simple_2.12-0.1.0-SNAPSHOT.jar_`...

**Comment by raboof** [comment]
(did it in #12)
